language: scala
dist: trusty
os: linux

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/.coursier/cache

jobs:
  include:
  - jdk: openjdk10
    scala: 2.11.12
  - jdk: openjdk8
    scala: 2.12.10
  - jdk: openjdk9
    scala: 2.13.1

before_install: ./.ci_scripts/beforeInstall.sh $TRAVIS_SCALA_VERSION
script: ./.ci_scripts/validate.sh
