version: 2.1

commands:
  setup_sbt:
    description: Get and install SBT
    parameters:
      sbt_version:
        type: string
        default: "1.3.8"
    steps:
      - run:
          name: Setup SBT
          command: |
                    if [ ! -x ~/sbt/bin/sbt ]; then
                      cd ~/
                      curl --silent -L -o sbt.tgz https://piccolo.link/sbt-<< parameters.sbt_version >>.tgz
                      tar -xzvf sbt.tgz && rm -f sbt.tgz
                    fi

  build_n_tests:
    description: Build & Run tests
    steps:
      - run:
          name: Build & Run tests
          command: |
                    export PATH=$PATH:~/sbt/bin
                    export USER=`basename $HOME`
                    
                    ./.ci_scripts/validate.sh

  collect_test_reports:
    description: Collect test reports
    steps:
      - run:
          name: Collect test report
          command: |
                    mkdir test-reports
                    find . -path '*/test-reports/*' -name '*.xml' \
                      -print -exec cp {} test-reports \;
          when: always


jobs:
  jdk10_scala211:
    docker:
      - image: circleci/openjdk:10-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.11.12
    
    steps:
      - checkout

      - setup_sbt

      - restore_cache:
          keys:
          - jdk10_scala211-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
          - dependencies-

      - build_n_tests

      - save_cache:
          paths:
            - $HOME/.ivy2
            - $HOME/.coursier/cache
            - $HOME/.sbt
            - $HOME/sbt
          key: jdk10_scala211-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}

      - collect_test_reports
      - store_test_results:
          path: test-reports

  jdk8_scala212:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.12.10
    
    steps:
      - checkout

      - setup_sbt

      - restore_cache:
          keys:
          - jdk8_scala212-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
          - dependencies-

      - build_n_tests

      - save_cache:
          paths:
            - $HOME/.ivy2
            - $HOME/.coursier/cache
            - $HOME/.sbt
            - $HOME/sbt
          key: jdk8_scala212-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}

      - collect_test_reports
      - store_test_results:
          path: test-reports

  jdk9_scala213:
    docker:
      - image: circleci/openjdk:9-jdk

    working_directory: ~/repo

    environment:
      SCALA_VERSION: 2.13.1
    
    steps:
      - checkout

      - setup_sbt

      - restore_cache:
          keys:
          - jdk9_scala213-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}
          - dependencies-

      - build_n_tests

      - save_cache:
          paths:
            - $HOME/.ivy2
            - $HOME/.coursier/cache
            - $HOME/.sbt
            - $HOME/sbt
          key: jdk9_scala213-{{ checksum "build.sbt" }}-{{ checksum "project/Dependencies.scala" }}

      - collect_test_reports
      - store_test_results:
          path: test-reports

workflows:
  version: 2

  scala_2_11:
    jobs:
      - jdk10_scala211

  scala_2_12:
    jobs:
      - jdk8_scala212

  scala_2_13:
    jobs:
      - jdk9_scala213

# TODO: Snapshot publish on master (nightly schedule?)